logging: 
  level: DEBUG
data_paths:
  corpus_text_path: data/MS-MARCO/subset_q10_d100/collection.jsonl
  emb_path: data/MS-MARCO/subset_q10_d100/collection_sentence-transformers-all-MiniLM-L6-v2.pkl
  queries_path: data/MS-MARCO/subset_q10_d100/queries.tsv
agent:
  agent_class: GeneralAgent
  policy: PipelinePolicy
  policy_steps:
    - component: DenseRetriever
      method: rank
llm:
  model_class: GeminiLLM
  model_name: gemini-1.5-flash
  template_dir: ../prompt_templates
embedding:
  embedder_class: HuggingFaceEmbedder
  model_name: sentence-transformers/all-MiniLM-L6-v2
knn:
  knn_class: ExactKNN
  sim_f: cosine
  k: 10
  implementation: load_all #load_all_in_batches or load_iteratively (for batch = 1) if corpus doesn't fit in memory